### ISSUE TITLE
Change from href to id in server

### ISSUE THREAD

**Issue by mhelvens** [open-physiology/lyph-server#15]

**Comment by albatros13** [comment]
This should be removed from the list. With transition to ID, assigning href is no longer relevant, but the equivalent function assignId should be in the db because it increases a counter that is a private attribute of a DB.

**Comment by mhelvens** [comment]
I don't understand the context of your comment.

**Comment by albatros13** [comment]
I commented a wrong issue I guess, I meant the issue about assignHref function is not relevant anymore in relation to this issue.
