### ISSUE TITLE
Refactor update operations where shortcut fields are reset

### ISSUE THREAD

**Issue by albatros13** [open-physiology/lyph-server#16]
Currently model library does not handle replacement of relationships reset via shortcuts, e.g.,
lyph relationship with material1 cannot be replaced to material2 or cleared by setting materials = [material2.id] or materials = []. Server can do it via replacing all relationships with neo4j queries, but the server instance of the model library will contain wrong relationships and the corresponding test will fail. After all relevant issues are fixed, uncomment the test and check that this issue is resolved.

**Comment by mhelvens** [comment]
As I mentioned on our call, this refactoring would be subsumed by something else we were planning to do, but I can't find the issue: Removing relationships as first-class citizens.

Point is: We don't need this issue, I think.
