### ISSUE TITLE
Revise tests to check properties and relations of extracted resources

### ISSUE THREAD

**Issue by albatros13** [open-physiology/lyph-server#17]
Some tests from testResources.spec.js  and testRelationships.spec.js fail because in REST API response we do not return entities with relationship shortcuts, they need to be replaced with full relationships.

**Comment by mhelvens** [comment]
blocked on new model library

**Comment by mhelvens** [comment]
Or it's not blocked. Tests can be written beforehand, and fail (or be skipped) until the model library is done.
