### ISSUE TITLE
Extract method assignHref from database class

### ISSUE THREAD

**Issue by albatros13** [open-physiology/lyph-server#6]

**Comment by albatros13** [comment]
This issue can be closed because: 
1) with transition to ID, assigning href is no longer needed.
2) The equivalent function assignId should be in the db class because it increases a counter that is a private attribute of a DB (it is equal 0 for an empty DB or the biggest id + 1 for an existing DB).

**Comment by mhelvens** [comment]
OK.

(Just to make sure: We never give id = 0 to any entity, right?)
